workflows:
  vitalink-android-workflow:
    name: VitaLink Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      # android_signing:
      #   - keystore_reference  # Uncomment and set up keystore in Codemagic UI for signed APK
      groups:
        - Supabase
      vars:
        PACKAGE_NAME: "org.aljasem.vitalink"
      node: 22.12.0
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Compile web code to www folder
        script: npm run build -- --configuration production
      - name: Add Android platform if not exists
        script: |
          if [ ! -d "android" ]; then
            # Install @capacitor/android if not already installed
            if ! npm list @capacitor/android > /dev/null 2>&1; then
              npm install @capacitor/android@^7.0.0
            fi
            npx cap add android
          fi
      - name: Update dependencies and copy web assets to native project
        script: |
          # npx cap copy # <- use this is you don't need to update native dependencies
          npx cap sync # <- update native dependencies and copy web assets to native project
      - name: Set Android SDK location
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Configure Java version for Android build
        script: |
          cd $CM_BUILD_DIR
          # Find and patch ALL build.gradle files in node_modules/@capacitor packages
          find node_modules/@capacitor -name "build.gradle" -type f | while read file; do
            if [ -f "$file" ]; then
              sed -i.bak 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' "$file"
              sed -i.bak 's/JavaLanguageVersion\.of(21)/JavaLanguageVersion.of(17)/g' "$file"
              sed -i.bak 's/sourceCompatibility.*21/sourceCompatibility JavaVersion.VERSION_17/g' "$file"
              sed -i.bak 's/targetCompatibility.*21/targetCompatibility JavaVersion.VERSION_17/g' "$file"
              rm -f "${file}.bak"
            fi
          done
          cd android
          # Update app/build.gradle to use Java 17 - comprehensive patching
          if [ -f "app/build.gradle" ]; then
            # Replace all Java 21 references with Java 17
            sed -i.bak 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' app/build.gradle
            sed -i.bak 's/JavaLanguageVersion\.of(21)/JavaLanguageVersion.of(17)/g' app/build.gradle
            sed -i.bak 's/sourceCompatibility.*21/sourceCompatibility JavaVersion.VERSION_17/g' app/build.gradle
            sed -i.bak 's/targetCompatibility.*21/targetCompatibility JavaVersion.VERSION_17/g' app/build.gradle
            sed -i.bak 's/sourceCompatibility = 21/sourceCompatibility = JavaVersion.VERSION_17/g' app/build.gradle
            sed -i.bak 's/targetCompatibility = 21/targetCompatibility = JavaVersion.VERSION_17/g' app/build.gradle
            # Force Java 17 - ensure compileOptions block exists and uses Java 17
            # Add compileOptions if it doesn't exist
            if ! grep -q "compileOptions" app/build.gradle && grep -q "android {" app/build.gradle; then
              awk '/android \{/ {print; print "    compileOptions {"; print "        sourceCompatibility JavaVersion.VERSION_17"; print "        targetCompatibility JavaVersion.VERSION_17"; print "    }"; next}1' app/build.gradle > app/build.gradle.tmp && mv app/build.gradle.tmp app/build.gradle
            fi
            # Update compileOptions to use Java 17 (only within compileOptions block)
            awk '/compileOptions \{/,/^    \}/ { 
              gsub(/sourceCompatibility.*/, "sourceCompatibility JavaVersion.VERSION_17")
              gsub(/targetCompatibility.*/, "targetCompatibility JavaVersion.VERSION_17")
              gsub(/JavaVersion\.VERSION_21/, "JavaVersion.VERSION_17")
            }1' app/build.gradle > app/build.gradle.tmp && mv app/build.gradle.tmp app/build.gradle
            rm -f app/build.gradle.bak app/build.gradle.tmp 2>/dev/null || true
          fi
          # Update root build.gradle
          if [ -f "build.gradle" ]; then
            sed -i.bak 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' build.gradle
            sed -i.bak 's/JavaLanguageVersion\.of(21)/JavaLanguageVersion.of(17)/g' build.gradle
            rm -f build.gradle.bak
          fi
          # Create Gradle init script to force Java 17 globally (in android directory)
          mkdir -p android/.gradle/init.d
          echo "allprojects {" > android/.gradle/init.d/java17.gradle
          echo "    tasks.withType(JavaCompile).configureEach {" >> android/.gradle/init.d/java17.gradle
          echo "        sourceCompatibility = JavaVersion.VERSION_17" >> android/.gradle/init.d/java17.gradle
          echo "        targetCompatibility = JavaVersion.VERSION_17" >> android/.gradle/init.d/java17.gradle
          echo "        options.release = 17" >> android/.gradle/init.d/java17.gradle
          echo "    }" >> android/.gradle/init.d/java17.gradle
          echo "}" >> android/.gradle/init.d/java17.gradle
          echo "subprojects {" >> android/.gradle/init.d/java17.gradle
          echo "    afterEvaluate { project ->" >> android/.gradle/init.d/java17.gradle
          echo "        if (project.hasProperty('android')) {" >> android/.gradle/init.d/java17.gradle
          echo "            project.android {" >> android/.gradle/init.d/java17.gradle
          echo "                compileOptions {" >> android/.gradle/init.d/java17.gradle
          echo "                    sourceCompatibility JavaVersion.VERSION_17" >> android/.gradle/init.d/java17.gradle
          echo "                    targetCompatibility JavaVersion.VERSION_17" >> android/.gradle/init.d/java17.gradle
          echo "                }" >> android/.gradle/init.d/java17.gradle
          echo "            }" >> android/.gradle/init.d/java17.gradle
          echo "        }" >> android/.gradle/init.d/java17.gradle
          echo "    }" >> android/.gradle/init.d/java17.gradle
          echo "}" >> android/.gradle/init.d/java17.gradle
          # Add global Java version override in root build.gradle as backup
          if [ -f "build.gradle" ] && ! grep -q "allprojects {" build.gradle; then
            echo "" >> build.gradle
            echo "allprojects {" >> build.gradle
            echo "    tasks.withType(JavaCompile).configureEach {" >> build.gradle
            echo "        sourceCompatibility = JavaVersion.VERSION_17" >> build.gradle
            echo "        targetCompatibility = JavaVersion.VERSION_17" >> build.gradle
            echo "        options.release = 17" >> build.gradle
            echo "    }" >> build.gradle
            echo "}" >> build.gradle
            echo "" >> build.gradle
            echo "subprojects {" >> build.gradle
            echo "    afterEvaluate { project ->" >> build.gradle
            echo "        if (project.hasProperty('android')) {" >> build.gradle
            echo "            project.android {" >> build.gradle
            echo "                compileOptions {" >> build.gradle
            echo "                    sourceCompatibility JavaVersion.VERSION_17" >> build.gradle
            echo "                    targetCompatibility JavaVersion.VERSION_17" >> build.gradle
            echo "                }" >> build.gradle
            echo "            }" >> build.gradle
            echo "        }" >> build.gradle
            echo "    }" >> build.gradle
            echo "}" >> build.gradle
          fi
      - name: Build Android release APK
        script: |
          # BUILD_NUMBER is a Codemagic built-in variable tracking the number
          # of times this workflow has been built
          cd $CM_BUILD_DIR/android
          if [ ! -f "./gradlew" ]; then
            echo "Error: gradlew not found. Android project may not be initialized properly."
            exit 1
          fi
          chmod +x ./gradlew
          ./gradlew assembleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=0.0.1.$BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ionic-builds@blonde.email
        notify:
          success: true
          failure: true