workflows:
  vitalink-android-workflow:
    name: VitaLink Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      # android_signing:
      #   - keystore_reference  # Uncomment and set up keystore in Codemagic UI for signed APK
      groups:
        - Supabase
      vars:
        PACKAGE_NAME: "org.aljasem.vitalink"
      node: 22.12.0
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Compile web code to www folder
        script: npm run build -- --configuration production
      - name: Add Android platform if not exists
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
      - name: Update dependencies and copy web assets to native project
        script: |
          # npx cap copy # <- use this is you don't need to update native dependencies
          npx cap sync # <- update native dependencies and copy web assets to native project
      - name: Set Android SDK location
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release APK
        script: |
          # BUILD_NUMBER is a Codemagic built-in variable tracking the number
          # of times this workflow has been built
          cd $CM_BUILD_DIR/android
          if [ ! -f "./gradlew" ]; then
            echo "Error: gradlew not found. Android project may not be initialized properly."
            exit 1
          fi
          chmod +x ./gradlew
          ./gradlew assembleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=0.0.1.$BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ionic-builds@blonde.email
        notify:
          success: true
          failure: true