workflows:
  vitalink-android-workflow:
    name: VitaLink Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      # android_signing:
      #   - vitalink_keystore
      # 
      # TO ENABLE AUTOMATIC SIGNING:
      # 1. Go to Codemagic → Your App → Code signing identities
      # 2. Add Android keystore with name: "vitalink_keystore"
      # 3. Upload your .jks or .keystore file and enter credentials:
      #    - Keystore password
      #    - Key alias
      #    - Key password
      # 4. Uncomment the android_signing lines above
      # 5. Save and rebuild
      #
      # Note: Without signing, you'll get unsigned APKs (fine for testing)
      #       Signed APKs are required for Play Store distribution
      groups:
        - Supabase
      vars:
        PACKAGE_NAME: "org.aljasem.vitalink"
      node: 22.12.0
      java: 21
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Compile web code to www folder
        script: npm run build -- --configuration production
      - name: Add Android platform if not exists
        script: |
          if [ ! -d "android" ]; then
            if ! npm list @capacitor/android > /dev/null 2>&1; then
              npm install @capacitor/android@^7.0.0
            fi
            npx cap add android
          fi
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Set Android SDK location
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Replace Android app icon with custom icon (remove Capacitor default)
        script: |
          cd $CM_BUILD_DIR
          echo "=== Replacing Capacitor default icons with custom VitaLink icons ==="
          
          # Ensure icon source exists
          if [ ! -f "src/assets/icon/icon-192x192.png" ]; then
            echo "ERROR: Custom icon not found at src/assets/icon/icon-192x192.png"
            exit 1
          fi
          
          # Create all mipmap directories
          mkdir -p android/app/src/main/res/mipmap-mdpi
          mkdir -p android/app/src/main/res/mipmap-hdpi
          mkdir -p android/app/src/main/res/mipmap-xhdpi
          mkdir -p android/app/src/main/res/mipmap-xxhdpi
          mkdir -p android/app/src/main/res/mipmap-xxxhdpi
          
          # Replace standard launcher icons (force overwrite)
          echo "Replacing standard launcher icons..."
          cp -f src/assets/icon/icon-72x72.png android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          cp -f src/assets/icon/icon-72x72.png android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          cp -f src/assets/icon/icon-96x96.png android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          cp -f src/assets/icon/icon-144x144.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          cp -f src/assets/icon/icon-192x192.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          
          # Replace round launcher icons (force overwrite)
          echo "Replacing round launcher icons..."
          cp -f src/assets/icon/icon-72x72.png android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
          cp -f src/assets/icon/icon-72x72.png android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
          cp -f src/assets/icon/icon-96x96.png android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
          cp -f src/assets/icon/icon-144x144.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
          cp -f src/assets/icon/icon-192x192.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
          
          # Replace adaptive icon foregrounds if they exist
          echo "Replacing adaptive icon foregrounds..."
          for density in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
            if [ -d "android/app/src/main/res/mipmap-${density}" ]; then
              # Adaptive icons use foreground and background layers
              if [ -f "android/app/src/main/res/mipmap-${density}/ic_launcher_foreground.png" ]; then
                cp -f src/assets/icon/icon-192x192.png android/app/src/main/res/mipmap-${density}/ic_launcher_foreground.png
              fi
              if [ -f "android/app/src/main/res/mipmap-${density}/ic_launcher_round_foreground.png" ]; then
                cp -f src/assets/icon/icon-192x192.png android/app/src/main/res/mipmap-${density}/ic_launcher_round_foreground.png
              fi
            fi
          done
          
          # Verify icons were replaced
          echo "Verifying icon replacement..."
          if [ -f "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png" ]; then
            echo "✓ Standard launcher icon replaced successfully"
          else
            echo "✗ WARNING: Standard launcher icon replacement may have failed"
          fi
          
          if [ -f "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png" ]; then
            echo "✓ Round launcher icon replaced successfully"
          else
            echo "✗ WARNING: Round launcher icon replacement may have failed"
          fi
          
          echo "=== Icon replacement complete ==="
      - name: Verify build files and environment
        script: |
          cd $CM_BUILD_DIR
          echo "=== Build Verification ==="
          echo "Checking www folder contents:"
          ls -la www/ | head -20
          echo ""
          echo "Checking if index.html exists:"
          [ -f "www/index.html" ] && echo "✓ index.html found" || echo "✗ index.html MISSING"
          echo ""
          echo "Checking environment files:"
          [ -f "src/environments/environment.prod.ts" ] && echo "✓ environment.prod.ts found" || echo "✗ environment.prod.ts MISSING"
          if [ -f "src/environments/environment.prod.ts" ]; then
            echo "Environment file contents (hiding sensitive data):"
            grep -E "(supabaseUrl|supabaseAnonKey)" src/environments/environment.prod.ts | sed 's/\(anonKey.*\):.*/\1: [REDACTED]/'
          fi
          echo ""
          echo "Checking Android assets:"
          [ -d "android/app/src/main/assets/public" ] && echo "✓ Android assets directory exists" || echo "✗ Android assets directory MISSING"
          if [ -d "android/app/src/main/assets/public" ]; then
            echo "Assets directory contents:"
            ls -la android/app/src/main/assets/public/ | head -10
          fi
      - name: Build Android debug APK (for easier debugging)
        script: |
          cd $CM_BUILD_DIR/android
          chmod +x ./gradlew
          # Build debug APK first for easier debugging
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=0.0.1.$BUILD_NUMBER
      - name: Build Android release APK (signed)
        script: |
          cd $CM_BUILD_DIR/android
          chmod +x ./gradlew
          # Build signed release APK using keystore from Codemagic
          ./gradlew assembleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=0.0.1.$BUILD_NUMBER
          echo "✓ Release APK built successfully"
          
      - name: Build Android App Bundle (AAB) for Play Store
        script: |
          cd $CM_BUILD_DIR/android
          chmod +x ./gradlew
          # Build signed AAB for Google Play Store
          ./gradlew bundleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=0.0.1.$BUILD_NUMBER
          echo "✓ Release AAB built successfully"
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - ionic-builds@blonde.email
        notify:
          success: true
          failure: true